"""
================================================================================
FILE: src/utils/video_processor.py
================================================================================

╔══════════════════════════════════════════════════════════════════════════════╗
║         🎓 FAANG-LEVEL LESSON: VIDEO PROCESSING, FFMPEG, AND OPENCV         ║
╚══════════════════════════════════════════════════════════════════════════════╝

WHAT IS THIS FILE?
──────────────────
Your video manipulation toolkit. This handles:
  1. Extracting the last frame (for scene continuity — your #1 pain point)
  2. Basic video info (duration, resolution, frame count)
  3. Trimming clips
  4. Quality upscaling of extracted frames

YOUR EXACT WORKFLOW AUTOMATED:
  Manual:  Select video → Pause at last frame → Screenshot → Crop → Save
  Auto:    processor.extract_continuation_frame("scene1.mp4")
           → Saves "scene1_last_frame.png" in 2 seconds


WHAT IS ffmpeg?
───────────────
ffmpeg is THE industry-standard command-line video processing tool.
Used by: YouTube, Netflix, TikTok, Instagram for all video encoding.

It's an external program (not Python), but Python can call it:
  subprocess.run(["ffmpeg", "-i", "video.mp4", ...])

OR using the ffmpeg-python library:
  import ffmpeg
  ffmpeg.input("video.mp4").output("output.png").run()

KEY ffmpeg operations:
  Extract frame: ffmpeg -i video.mp4 -vf "select=eq(n,99)" frame.png
  Get duration:  ffprobe -v q -of json -show_streams video.mp4
  Trim video:    ffmpeg -ss 0 -i video.mp4 -t 3 -o clip.mp4

Install ffmpeg: https://ffmpeg.org/download.html (add to PATH)
Then: pip install ffmpeg-python


WHAT IS subprocess? (Running system commands from Python)
──────────────────────────────────────────────────────────
subprocess lets you run terminal commands FROM Python code.

  import subprocess
  result = subprocess.run(
      ["ffmpeg", "-version"],      # Command + args as a list
      capture_output=True,         # Capture stdout/stderr
      text=True,                   # Return strings instead of bytes
      check=True,                  # Raise exception if command fails (non-zero exit)
  )
  print(result.stdout)  # ffmpeg version 6.0...

This is how ALL automation tools work at a low level:
  - GitHub Actions runs shell commands
  - Docker runs commands in containers
  - CI/CD pipelines chain commands together

At FAANG:
  build_system.run_command(["make", "build"])  # Same concept, production scale


WHAT IS OpenCV? (cv2)
──────────────────────
cv2 is Python's OpenCV binding — the most powerful computer vision library.
Used by: Google Photos, Amazon Rekognition, self-driving cars.

For video specifically:
  cap = cv2.VideoCapture("video.mp4")  # Open video
  fps = cap.get(cv2.CAP_PROP_FPS)      # Get frames per second
  width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
  height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
  total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
  duration_seconds = total_frames / fps

  # Read all frames:
  while True:
      ret, frame = cap.read()  # ret = success bool, frame = numpy array
      if not ret:              # No more frames
          break
      # Do something with frame...

  cap.release()  # ALWAYS release when done (closes the file)


WHAT IS A NUMPY ARRAY? (How images are really stored)
───────────────────────────────────────────────────────
When cv2 reads a frame, it's actually a numpy array.
  frame.shape  # → (1080, 1920, 3) = height × width × channels

Each pixel has 3 values [Blue, Green, Red] (cv2 uses BGR, not RGB!)
  pixel = frame[100, 200]  # → array([128, 200, 50]) = one pixel's BGR values

For upscaling you need Real-ESRGAN or ESRGAN (AI upscaling):
  pip install realesrgan  # Free AI upscaling, used by Topaz AI competitors

Or use a simpler cubic interpolation:
  cv2.resize(frame, (new_w, new_h), interpolation=cv2.INTER_CUBIC)
  # INTER_CUBIC = best quality for upscaling (bilinear interpolation)


VIDEO CONTINUITY WORKFLOW (Your main automation goal)
──────────────────────────────────────────────────────
Here's your COMPLETE automated workflow when done:

  # After scene 1 video is generated by AI:
  processor = VideoProcessor()

  # Step 1: Extract last frame automatically
  last_frame = processor.extract_continuation_frame("scene1_output.mp4")

  # Step 2: Auto-check quality
  if not image_processor.is_quality_sufficient(last_frame):
      print("⚠️ Frame is low quality. Upscaling...")
      last_frame = processor.upscale_frame(last_frame)

  # Step 3: Register frame for next scene
  scene1.set_continuation_frame(str(last_frame))
  scene2 = scene1.create_continuation()
  scene2.characters[0].dialogue = "Relax, Mango…"

  # Step 4: Generate scene 2 prompt
  print(scene2.generate_video_prompt())
  # Done! Copy-paste into AI video generator.


WHY TWO LIBRARIES (cv2 AND ffmpeg)?
────────────────────────────────────
cv2: Better for READING frames and image manipulation (Python native)
ffmpeg: Better for WRITING videos and complex encoding operations

At FAANG:
  - Video READING/ANALYSIS → OpenCV (faster, more control)
  - Video ENCODING/CONVERTING → FFmpeg (handles all formats)
  - The two complement each other

================================================================================
"""

import logging
import subprocess
from pathlib import Path
from typing import Optional, Dict, Any, Tuple

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# TODO 1: Install OpenCV and extract the last frame from one of your videos
#   pip install opencv-python
#   cap = cv2.VideoCapture("your_scene.mp4")
#   # Loop until no more frames, save the last one
#
# TODO 2: Add a method "get_video_info(video_path)" that returns:
#   {"width": 1920, "height": 1080, "fps": 30, "duration": 6.0, "frames": 180}
#
# TODO 3: Add a method "trim_video(input, start_sec, end_sec, output)"
#   that calls ffmpeg to trim a video to specific timestamps
#
# TODO 4: Implement upscale_with_cubic(image_path, scale=2) using cv2.resize()
#   cv2.resize(img, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
#   This doubles the image size with best quality interpolation
#
# TODO 5: Add "batch_extract_last_frames(video_folder)" that processes
#   every video in a folder and saves all last frames
# ─────────────────────────────────────────────────────────────────────────────


# ═══════════════════════════════════════════════════════════════════════════
# FULL CODE (try it yourself first!)
# ═══════════════════════════════════════════════════════════════════════════

# class VideoProcessor:
#     """
#     Video manipulation toolkit for the Fruit Love Island pipeline.
#
#     Automates your most painful workflow step:
#     "Screenshot the last frame to continue the video scene."
#
#     Usage:
#         processor = VideoProcessor()
#         frame_path = processor.extract_continuation_frame("scene1.mp4")
#         info = processor.get_video_info("scene1.mp4")
#         print(f"Duration: {info['duration']}s at {info['fps']} FPS")
#     """
#
#     def __init__(self, output_dir: str = "assets/frames"):
#         self.output_dir = Path(output_dir)
#         self.output_dir.mkdir(parents=True, exist_ok=True)
#         self._has_cv2 = self._check_cv2()
#         self._has_ffmpeg = self._check_ffmpeg()
#
#     def _check_cv2(self) -> bool:
#         """Check if OpenCV is available."""
#         try:
#             import cv2
#             logger.info(f"OpenCV: ✅ Available (v{cv2.__version__})")
#             return True
#         except ImportError:
#             logger.warning("OpenCV not available. Run: pip install opencv-python")
#             return False
#
#     def _check_ffmpeg(self) -> bool:
#         """Check if ffmpeg is available in system PATH."""
#         try:
#             result = subprocess.run(
#                 ["ffmpeg", "-version"],
#                 capture_output=True,
#                 timeout=5
#             )
#             if result.returncode == 0:
#                 logger.info("FFmpeg: ✅ Available")
#                 return True
#         except (FileNotFoundError, subprocess.TimeoutExpired):
#             pass
#         logger.warning("FFmpeg not found in PATH. Install from: https://ffmpeg.org")
#         return False
#
#     def extract_continuation_frame(
#         self,
#         video_path: str,
#         output_name: Optional[str] = None,
#     ) -> Path:
#         """
#         Extract the VERY LAST FRAME from a video.
#
#         THIS IS YOUR #1 AUTOMATION WIN.
#         This replaces: pause at end → screenshot → crop → save
#
#         Strategy: Try cv2 first (faster). Fall back to ffmpeg (more compatible).
#
#         Args:
#             video_path: Path to your video file (mp4, mov, webm, etc.)
#             output_name: Output filename (auto-named if not provided)
#
#         Returns:
#             Path: Path to the extracted frame PNG image.
#
#         Raises:
#             RuntimeError: If neither cv2 nor ffmpeg can process the file.
#         """
#         if self._has_cv2:
#             return self._extract_last_frame_cv2(video_path, output_name)
#         elif self._has_ffmpeg:
#             return self._extract_last_frame_ffmpeg(video_path, output_name)
#         else:
#             raise RuntimeError(
#                 "Cannot extract frame: neither OpenCV nor FFmpeg is available.\n"
#                 "Install one: pip install opencv-python  OR  https://ffmpeg.org"
#             )
#
#     def _extract_last_frame_cv2(
#         self,
#         video_path: str,
#         output_name: Optional[str] = None,
#     ) -> Path:
#         """Extract last frame using OpenCV (primary method)."""
#         import cv2
#
#         cap = cv2.VideoCapture(str(video_path))
#         if not cap.isOpened():
#             raise ValueError(f"Could not open video: {video_path}")
#
#         total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
#         logger.debug(f"Video has {total_frames} frames")
#
#         # Jump to last frame
#         cap.set(cv2.CAP_PROP_POS_FRAMES, max(0, total_frames - 1))
#         ret, frame = cap.read()
#
#         if not ret:
#             # Fallback: read through all frames
#             logger.warning("Direct seek failed. Reading through all frames...")
#             cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
#             last_frame = None
#             while True:
#                 ret, frame = cap.read()
#                 if not ret:
#                     break
#                 last_frame = frame
#             frame = last_frame
#
#         cap.release()
#
#         if frame is None:
#             raise RuntimeError(f"Could not extract any frame from: {video_path}")
#
#         if output_name is None:
#             stem = Path(video_path).stem
#             output_name = f"{stem}_continuation_frame.png"
#
#         output_path = self.output_dir / output_name
#         cv2.imwrite(str(output_path), frame)
#
#         logger.info(f"✅ Continuation frame extracted (cv2): {output_path}")
#         print(f"✅ Last frame saved: {output_path}")
#         return output_path
#
#     def _extract_last_frame_ffmpeg(
#         self,
#         video_path: str,
#         output_name: Optional[str] = None,
#     ) -> Path:
#         """Extract last frame using FFmpeg (fallback method)."""
#         if output_name is None:
#             stem = Path(video_path).stem
#             output_name = f"{stem}_continuation_frame.png"
#
#         output_path = self.output_dir / output_name
#
#         # ffmpeg command to grab the very last frame
#         # -sseof -0.1: seek to 0.1s before end
#         # -update 1: overwrite output each frame (get only last)
#         cmd = [
#             "ffmpeg", "-y",           # -y: overwrite output without asking
#             "-sseof", "-0.1",         # Seek to near end
#             "-i", str(video_path),    # Input file
#             "-update", "1",           # Update single image (keeps only last)
#             "-q:v", "1",              # Highest quality
#             str(output_path),          # Output file
#         ]
#
#         result = subprocess.run(cmd, capture_output=True, text=True)
#
#         if result.returncode != 0:
#             raise RuntimeError(
#                 f"FFmpeg failed: {result.stderr[:500]}"
#             )
#
#         logger.info(f"✅ Continuation frame extracted (ffmpeg): {output_path}")
#         print(f"✅ Last frame saved: {output_path}")
#         return output_path
#
#     def get_video_info(self, video_path: str) -> Dict[str, Any]:
#         """
#         Get technical information about a video file.
#
#         Returns:
#             dict with: width, height, fps, duration_seconds, frame_count, format
#         """
#         if not self._has_cv2:
#             logger.warning("cv2 required for video info. Run: pip install opencv-python")
#             return {}
#
#         import cv2
#         cap = cv2.VideoCapture(str(video_path))
#
#         if not cap.isOpened():
#             raise ValueError(f"Could not open video: {video_path}")
#
#         fps = cap.get(cv2.CAP_PROP_FPS)
#         total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
#         width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
#         height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
#         cap.release()
#
#         duration = total_frames / fps if fps > 0 else 0
#
#         info = {
#             "width": width,
#             "height": height,
#             "fps": round(fps, 2),
#             "duration_seconds": round(duration, 2),
#             "frame_count": total_frames,
#             "resolution": f"{width}x{height}",
#         }
#
#         logger.info(f"Video info for {Path(video_path).name}: {info}")
#         return info
#
#     def upscale_frame_cubic(
#         self,
#         image_path: str,
#         scale_factor: float = 2.0,
#         output_name: Optional[str] = None,
#     ) -> Path:
#         """
#         Upscale an image using cubic interpolation.
#
#         YOUR USE CASE: "Sometimes the screenshot is low quality, so I put it
#         into Gemini AI to make it higher quality."
#
#         This automates a basic upscale. For AI upscaling, you'd call
#         a Real-ESRGAN model or an API like Stability AI's upscaler.
#
#         Args:
#             image_path: Path to the image to upscale
#             scale_factor: How much to scale up (2.0 = double size)
#             output_name: Output filename
#
#         Returns:
#             Path: Path to the upscaled image.
#         """
#         import cv2
#         import numpy as np
#
#         img = cv2.imread(str(image_path))
#         if img is None:
#             raise ValueError(f"Could not read image: {image_path}")
#
#         original_h, original_w = img.shape[:2]
#         new_w = int(original_w * scale_factor)
#         new_h = int(original_h * scale_factor)
#
#         # INTER_LANCZOS4 = best quality upscaling algorithm in cv2
#         upscaled = cv2.resize(img, (new_w, new_h), interpolation=cv2.INTER_LANCZOS4)
#
#         if output_name is None:
#             stem = Path(image_path).stem
#             output_name = f"{stem}_upscaled_{int(scale_factor)}x.png"
#
#         output_path = self.output_dir / output_name
#         cv2.imwrite(str(output_path), upscaled)
#
#         logger.info(
#             f"✅ Upscaled {original_w}x{original_h} → {new_w}x{new_h}: {output_path}"
#         )
#         print(f"✅ Upscaled: {output_path}")
#         return output_path
#
#
# # ─────────────────────────────────────────────────────────────────────────────
# # EXAMPLE: python src/utils/video_processor.py
# # ─────────────────────────────────────────────────────────────────────────────
# if __name__ == "__main__":
#     processor = VideoProcessor()
#
#     # Uncomment and replace with your file paths to test:
#     # frame = processor.extract_continuation_frame("path/to/your/scene.mp4")
#     # info = processor.get_video_info("path/to/your/scene.mp4")
#     # print(info)
#
#     print("VideoProcessor ready. Replace the paths above to test with your files.")
